import { Injectable, NotFoundException } from '@nestjs/common';
import PDFDocument from 'pdfkit';
import { BillingService } from '../billing/billing.service';

@Injectable()
export class PdfService {
  constructor(
    private readonly billingService: BillingService,
  ) {}

  async generateBillingInvoice(
    billingId: string,
  ): Promise<Buffer> {
    const billing = await this.billingService.findInvoiceData(
      billingId,
    );

    if (!billing) {
      throw new NotFoundException('Billing not found');
    }

    return new Promise((resolve) => {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 50,
      });

      const buffers: Buffer[] = [];

      doc.on('data', (d) => buffers.push(d));

      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });

      // Header
      doc
        .fontSize(24)
        .text('ORANGE FIBERNET', {
          align: 'center',
        });

      doc
        .fontSize(18)
        .text('TAX INVOICE', {
          align: 'center',
        });

      doc.moveDown(2);

      doc.fontSize(12);

      doc.text(`Invoice No : ${billing.invoiceNumber}`);

      doc.text(
        `Customer : ${billing.subscription.customer.fullName}`,
      );

      doc.text(
        `Package : ${billing.subscription.package.name}`,
      );

      doc.text(
        `Amount : ₹${billing.amount}`,
      );

      doc.text(
        `GST : ₹${billing.gstAmount}`,
      );

      doc.text(
        `Total : ₹${billing.totalAmount}`,
      );

      doc.text(
        `Due Date : ${billing.dueDate.toDateString()}`,
      );

      doc.text(
        `Status : ${billing.status}`,
      );

      doc.moveDown();

      doc.text(
        '---------------------------------------------',
      );

      doc.moveDown();

      doc.text(
        'Generated by OrangeERP',
        {
          align: 'center',
        },
      );

      doc.end();
    });
  }
}